channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.2
  - cython
  - ipython
  - ipyparallel
  - ipywidgets
  - numpy
  - matplotlib
  - mpi4py
  - networkx
  - pandas
  - scikit-image
  - scikit-learn
  - sympy
  - lxml
  - beautifulsoup4
  - requests-html
