channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - cython
  - ipython
  - ipyparallel
  - ipywidgets
  - numpy
  - matplotlib
  - mpi4py
  - networkx
  - pandas
  - scikit-image
  - scikit-learn
  - sympy
